package com.github.kunseru.bloodhuntapiserver.sessions;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/sessions/regions/{version}")
public class SessionsRegions {

    @GetMapping
    public String getLiveRegions(@PathVariable String version) {
        return "{\n" +
                "   \"availableRegions\":[\n" +
                "      {\n" +
                "         \"regionName\":\"asia-southeast1\",\n" +
                "         \"regionId\":\"449a5c5a-dac2-11e9-9799-7550ae191afe\",\n" +
                "         \"pingServers\":[\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"107.6.114.196\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"174.127.69.63\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"35.240.253.104\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"35.187.249.80\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            }\n" +
                "         ]\n" +
                "      },\n" +
                "      {\n" +
                "         \"regionName\":\"australia-southeast1\",\n" +
                "         \"regionId\":\"44a0389a-dac2-11e9-8bf6-277426f8e39e\",\n" +
                "         \"pingServers\":[\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"137.59.252.82\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"27.50.80.197\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"143.244.63.209\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"108.181.64.217\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"146.185.236.19\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.116.125.134\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"35.201.13.194\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            }\n" +
                "         ]\n" +
                "      },\n" +
                "      {\n" +
                "         \"regionName\":\"europe\",\n" +
                "         \"regionId\":\"449d0132-dac2-11e9-b9d0-2b2a99ffa0c3\",\n" +
                "         \"pingServers\":[\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"107.6.143.222\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"23.109.140.20\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"185.225.208.58\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.142.13.196\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"37.61.211.59\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            }\n" +
                "         ]\n" +
                "      },\n" +
                "      {\n" +
                "         \"regionName\":\"southamerica-east1\",\n" +
                "         \"regionId\":\"44a1b5f0-dac2-11e9-b90d-43e9a6bcb22f\",\n" +
                "         \"pingServers\":[\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"177.54.157.81\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"128.1.239.210\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"108.181.136.81\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"213.156.149.237\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.95.162.84\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.151.205.180\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.151.216.166\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            }\n" +
                "         ]\n" +
                "      },\n" +
                "      {\n" +
                "         \"regionName\":\"us-west1\",\n" +
                "         \"regionId\":\"449752d7-dac2-11e9-bcf5-1115a83e2153\",\n" +
                "         \"pingServers\":[\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"206.191.149.116\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"174.127.114.34\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"64.58.125.4\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"66.206.17.186\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"207.188.6.44\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"87.249.136.66\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"172.241.228.151\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.133.98.138\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"35.238.15.163\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.72.210.106\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"34.133.218.111\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"198.147.23.198\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            },\n" +
                "            {\n" +
                "               \"pingServerIpV4\":\"199.71.214.79\",\n" +
                "               \"pingServerPort\":9000\n" +
                "            }\n" +
                "         ]\n" +
                "      }\n" +
                "   ],\n" +
                "   \"ok\":true,\n" +
                "   \"retryable\":false,\n" +
                "   \"error\":null\n" +
                "}";
    }
}
